[phases.setup]
aptPkgs = [
    "php8.0-fpm",
    "php8.0-mysql",
    "php8.0-mbstring",
    "php8.0-xml",
    "php8.0-curl",
    "nginx"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php-fpm && nginx -g 'daemon off;'"
