defaultPlacement: end
fieldLayouts:
  00b384c1-035d-436b-a06e-0d01b09dc664:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 5e759dbe-398d-4a2f-be1b-1d595102e8ac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7740fc7a-ed9e-40a5-a161-72f02a7127f6
        userCondition: null
handle: recipeType
name: 'Recipe Type'
siteSettings:
  1d4f7b35-8c8e-4488-9d9b-b16d04f67c83: # Recipe Hub
    hasUrls: true
    template: recipe-type/_entry.twig
    uriFormat: 'recipe-type/{slug}'
structure:
  maxLevels: null
  uid: 91bf9fc1-ec78-4f80-a1ba-7962705574c7
