columnSuffix: null
contentColumnType: string
fieldGroup: a625fd61-2f2f-4b9e-a4a3-d409f9594393 # Recipes
handle: ingredients
instructions: null
name: Ingredients
searchable: false
settings:
  contentTable: '{{%matrixcontent_ingredients}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
