columnSuffix: obofttsb
contentColumnType: integer(10)
fieldGroup: a625fd61-2f2f-4b9e-a4a3-d409f9594393 # Recipes
handle: page
instructions: null
name: Page
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
