columnSuffix: null
contentColumnType: string
fieldGroup: a625fd61-2f2f-4b9e-a4a3-d409f9594393 # Recipes
handle: recipeType
instructions: null
name: 'Recipe Type'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:d2d28f7b-04c0-4f93-96c2-8e9acbecdcef' # Recipe Type
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
